// Package Declaration
package me.iffa.bananaspace.gui;

// Java Imports
import javax.swing.JOptionPane;

// BananaSpace Imports
import me.iffa.bananaspace.BananaSpace;

/**
 * Window for creating new space worlds with the Pail GUI.
 * 
 * @author iffa
 */
public class PailCreateWorld extends javax.swing.JFrame {
    // Variables

    private BananaSpace plugin;
    // Constructor

    public PailCreateWorld(BananaSpace plugin) {
        this.plugin = plugin;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        WorldNameBox = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Create a spaceworld");
        jLabel1.setToolTipText("Simply specify a name for the space world and click create. The world will be created for you.");

        WorldNameBox.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        WorldNameBox.setText("New spaceworld name");
        WorldNameBox.setToolTipText("Specify a name for the spaceworld. Must not be a world already, and must not be empty.");

        CreateButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(WorldNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CreateButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorldNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
// TODO add your handling code here:
    if (plugin.getServer().getWorld(WorldNameBox.getText()) != null) {
        JOptionPane.showMessageDialog(this, "A world with the given name already exists!", "Invalid world name", JOptionPane.WARNING_MESSAGE);
        return;
    }
    BananaSpace.worldHandler.createSpaceWorld(plugin, WorldNameBox.getText(), false);
    BananaSpace.pailInt.addSpaceList(WorldNameBox.getText());
    JOptionPane.showMessageDialog(this, "A new spaceworld called '" + WorldNameBox.getText() + "' has been created!", "Spaceworld created", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_CreateButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField WorldNameBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
